// scripts/generate-fonts-meta.ts

import * as fs from "fs";
import * as path from "path";

const FONTS_DIR = path.join(process.cwd(), "public", "fonts");
const OUTPUT_FILE = path.join(process.cwd(), "src", "lib", "figlet", "fonts-meta.ts");

interface FontMeta {
  id: string;
  name: string;
  style: string;
  heightLevel: 1 | 2 | 3;
}

function parseHeaderHeight(content: string): number {
  const match = content.match(/^flf2a\$\s+(\d+)/m);
  return match ? parseInt(match[1], 10) : 5;
}

function guessStyle(filename: string): string {
  const lower = filename.toLowerCase();
  if (/3d|relief|shadow|emboss/i.test(lower)) return "3d";
  if (/script|cursive|hand|decorative|calig/i.test(lower)) return "script";
  if (/block|banner|thick|bold/i.test(lower)) return "block";
  if (/retro|term|dos|classic|basic/i.test(lower)) return "retro";
  if (/thin|slim|lean|light/i.test(lower)) return "thin";
  if (/fun|weird|cyber|digital|star/i.test(lower)) return "fun";
  return "classic";
}

function heightToLevel(height: number): 1 | 2 | 3 {
  if (height <= 3) return 1;
  if (height >= 8) return 3;
  return 2;
}

async function main() {
  const files = fs.readdirSync(FONTS_DIR).filter(f => f.endsWith(".flf"));

  const fonts: FontMeta[] = files.map(filename => {
    const content = fs.readFileSync(path.join(FONTS_DIR, filename), "utf8");
    const id = filename.replace(/\.flf$/i, "");
    const name = id.replace(/[-_]/g, " ").replace(/\b\w/g, c => c.toUpperCase());
    const height = parseHeaderHeight(content);
    return {
      id,
      name,
      style: guessStyle(filename),
      heightLevel: heightToLevel(height),
    };
  });

  const code = `// AUTO-GENERATED by scripts/generate-fonts-meta.ts
// Do not edit manually

export type FontStyle = "classic" | "3d" | "script" | "block" | "retro" | "fun" | "thin";

export interface FontMeta {
  id: string;
  name: string;
  style: FontStyle;
  heightLevel: 1 | 2 | 3;
}

export const allFontsMeta: FontMeta[] = ${JSON.stringify(fonts, null, 2)} as const;

export function getFontById(id: string): FontMeta | undefined {
  return allFontsMeta.find(f => f.id === id);
}
`;

  fs.writeFileSync(OUTPUT_FILE, code);
  console.log(`Generated ${fonts.length} font entries -> ${OUTPUT_FILE}`);
}

main().catch(console.error);
