// AUTO-GENERATED by scripts/generate-fonts-meta.ts
// Do not edit manually

export type FontStyle = "classic" | "3d" | "script" | "block" | "retro" | "fun" | "thin";

export interface FontMeta {
  id: string;
  name: string;
  style: FontStyle;
  heightLevel: 1 | 2 | 3;
}

export const allFontsMeta: FontMeta[] = [
  {
    "id": "1Row",
    "name": "1Row",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "3-D",
    "name": "3 D",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "3D Diagonal",
    "name": "3D Diagonal",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "3D-ASCII",
    "name": "3D ASCII",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "3d",
    "name": "3d",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "3d_diagonal",
    "name": "3d Diagonal",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "3x5",
    "name": "3x5",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "4Max",
    "name": "4Max",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "5 Line Oblique",
    "name": "5 Line Oblique",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "5lineoblique",
    "name": "5lineoblique",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "AMC 3 Line",
    "name": "AMC 3 Line",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "AMC 3 Liv1",
    "name": "AMC 3 Liv1",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "AMC AAA01",
    "name": "AMC AAA01",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "AMC Neko",
    "name": "AMC Neko",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "AMC Razor",
    "name": "AMC Razor",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "AMC Razor2",
    "name": "AMC Razor2",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "AMC Slash",
    "name": "AMC Slash",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "AMC Slider",
    "name": "AMC Slider",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "AMC Thin",
    "name": "AMC Thin",
    "style": "thin",
    "heightLevel": 2
  },
  {
    "id": "AMC Tubes",
    "name": "AMC Tubes",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "AMC Untitled",
    "name": "AMC Untitled",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "ANSI Regular",
    "name": "ANSI Regular",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "ANSI Shadow",
    "name": "ANSI Shadow",
    "style": "3d",
    "heightLevel": 2
  },
  {
    "id": "ASCII New Roman",
    "name": "ASCII New Roman",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Acrobatic",
    "name": "Acrobatic",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Alligator",
    "name": "Alligator",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Alligator2",
    "name": "Alligator2",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Alpha",
    "name": "Alpha",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Alphabet",
    "name": "Alphabet",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Arrows",
    "name": "Arrows",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Avatar",
    "name": "Avatar",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "B1FF",
    "name": "B1FF",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Banner",
    "name": "Banner",
    "style": "block",
    "heightLevel": 3
  },
  {
    "id": "Banner3-D",
    "name": "Banner3 D",
    "style": "block",
    "heightLevel": 3
  },
  {
    "id": "Banner3",
    "name": "Banner3",
    "style": "block",
    "heightLevel": 2
  },
  {
    "id": "Banner4",
    "name": "Banner4",
    "style": "block",
    "heightLevel": 2
  },
  {
    "id": "Barbwire",
    "name": "Barbwire",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Basic",
    "name": "Basic",
    "style": "retro",
    "heightLevel": 3
  },
  {
    "id": "Bear",
    "name": "Bear",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Bell",
    "name": "Bell",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Benjamin",
    "name": "Benjamin",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Big Chief",
    "name": "Big Chief",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Big Money-ne",
    "name": "Big Money Ne",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Big Money-nw",
    "name": "Big Money Nw",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Big Money-se",
    "name": "Big Money Se",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Big Money-sw",
    "name": "Big Money Sw",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Big",
    "name": "Big",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Bigfig",
    "name": "Bigfig",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Binary",
    "name": "Binary",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Block",
    "name": "Block",
    "style": "block",
    "heightLevel": 3
  },
  {
    "id": "Blocks",
    "name": "Blocks",
    "style": "block",
    "heightLevel": 3
  },
  {
    "id": "Bloody",
    "name": "Bloody",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Bolger",
    "name": "Bolger",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Braced",
    "name": "Braced",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Bright",
    "name": "Bright",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Broadway KB",
    "name": "Broadway KB",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Broadway",
    "name": "Broadway",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Bubble",
    "name": "Bubble",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Bulbhead",
    "name": "Bulbhead",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Caligraphy",
    "name": "Caligraphy",
    "style": "script",
    "heightLevel": 3
  },
  {
    "id": "Caligraphy2",
    "name": "Caligraphy2",
    "style": "script",
    "heightLevel": 3
  },
  {
    "id": "Calvin S",
    "name": "Calvin S",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Cards",
    "name": "Cards",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Catwalk",
    "name": "Catwalk",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Chiseled",
    "name": "Chiseled",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Chunky",
    "name": "Chunky",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Coinstak",
    "name": "Coinstak",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Cola",
    "name": "Cola",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Colossal",
    "name": "Colossal",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Computer",
    "name": "Computer",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Contessa",
    "name": "Contessa",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Contrast",
    "name": "Contrast",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Cosmike",
    "name": "Cosmike",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Crawford",
    "name": "Crawford",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Crawford2",
    "name": "Crawford2",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Crazy",
    "name": "Crazy",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Cricket",
    "name": "Cricket",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Cursive",
    "name": "Cursive",
    "style": "script",
    "heightLevel": 2
  },
  {
    "id": "Cyberlarge",
    "name": "Cyberlarge",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "Cybermedium",
    "name": "Cybermedium",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "Cybersmall",
    "name": "Cybersmall",
    "style": "fun",
    "heightLevel": 1
  },
  {
    "id": "Cygnet",
    "name": "Cygnet",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "DANC4",
    "name": "DANC4",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "DOS Rebel",
    "name": "DOS Rebel",
    "style": "retro",
    "heightLevel": 3
  },
  {
    "id": "DWhistled",
    "name": "DWhistled",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Dancing Font",
    "name": "Dancing Font",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Decimal",
    "name": "Decimal",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Def Leppard",
    "name": "Def Leppard",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Delta Corps Priest 1",
    "name": "Delta Corps Priest 1",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Diamond",
    "name": "Diamond",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Diet Cola",
    "name": "Diet Cola",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Digital",
    "name": "Digital",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "Doh",
    "name": "Doh",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Doom",
    "name": "Doom",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Dot Matrix",
    "name": "Dot Matrix",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Double Shorts",
    "name": "Double Shorts",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Double",
    "name": "Double",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Dr Pepper",
    "name": "Dr Pepper",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Efti Chess",
    "name": "Efti Chess",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Efti Font",
    "name": "Efti Font",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Efti Italic",
    "name": "Efti Italic",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Efti Piti",
    "name": "Efti Piti",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Efti Robot",
    "name": "Efti Robot",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Efti Wall",
    "name": "Efti Wall",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Efti Water",
    "name": "Efti Water",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Electronic",
    "name": "Electronic",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Elite",
    "name": "Elite",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Epic",
    "name": "Epic",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Fender",
    "name": "Fender",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Filter",
    "name": "Filter",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Fire Font-k",
    "name": "Fire Font K",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Fire Font-s",
    "name": "Fire Font S",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Flipped",
    "name": "Flipped",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Flower Power",
    "name": "Flower Power",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Four Tops",
    "name": "Four Tops",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Fraktur",
    "name": "Fraktur",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Fun Face",
    "name": "Fun Face",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "Fun Faces",
    "name": "Fun Faces",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "Fuzzy",
    "name": "Fuzzy",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Georgi16",
    "name": "Georgi16",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Georgia11",
    "name": "Georgia11",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Ghost",
    "name": "Ghost",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Ghoulish",
    "name": "Ghoulish",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Glenyn",
    "name": "Glenyn",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Goofy",
    "name": "Goofy",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Gothic",
    "name": "Gothic",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Graceful",
    "name": "Graceful",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Gradient",
    "name": "Gradient",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Graffiti",
    "name": "Graffiti",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Greek",
    "name": "Greek",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Heart Left",
    "name": "Heart Left",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Heart Right",
    "name": "Heart Right",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Henry 3D",
    "name": "Henry 3D",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "Hex",
    "name": "Hex",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Hieroglyphs",
    "name": "Hieroglyphs",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Hollywood",
    "name": "Hollywood",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Horizontal Left",
    "name": "Horizontal Left",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Horizontal Right",
    "name": "Horizontal Right",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "ICL-1900",
    "name": "ICL 1900",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Impossible",
    "name": "Impossible",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Invita",
    "name": "Invita",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Isometric1",
    "name": "Isometric1",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Isometric2",
    "name": "Isometric2",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Isometric3",
    "name": "Isometric3",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Isometric4",
    "name": "Isometric4",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Italic",
    "name": "Italic",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Ivrit",
    "name": "Ivrit",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "JS Block Letters",
    "name": "JS Block Letters",
    "style": "block",
    "heightLevel": 1
  },
  {
    "id": "JS Bracket Letters",
    "name": "JS Bracket Letters",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "JS Capital Curves",
    "name": "JS Capital Curves",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "JS Cursive",
    "name": "JS Cursive",
    "style": "script",
    "heightLevel": 2
  },
  {
    "id": "JS Stick Letters",
    "name": "JS Stick Letters",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Jacky",
    "name": "Jacky",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Jazmine",
    "name": "Jazmine",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Jerusalem",
    "name": "Jerusalem",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Katakana",
    "name": "Katakana",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Kban",
    "name": "Kban",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Keyboard",
    "name": "Keyboard",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Knob",
    "name": "Knob",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Konto Slant",
    "name": "Konto Slant",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Konto",
    "name": "Konto",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "LCD",
    "name": "LCD",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Larry 3D 2",
    "name": "Larry 3D 2",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "Larry 3D",
    "name": "Larry 3D",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "Lean",
    "name": "Lean",
    "style": "thin",
    "heightLevel": 3
  },
  {
    "id": "Letters",
    "name": "Letters",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Lil Devil",
    "name": "Lil Devil",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Line Blocks",
    "name": "Line Blocks",
    "style": "block",
    "heightLevel": 2
  },
  {
    "id": "Linux",
    "name": "Linux",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Lockergnome",
    "name": "Lockergnome",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Madrid",
    "name": "Madrid",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Marquee",
    "name": "Marquee",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Maxfour",
    "name": "Maxfour",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Merlin1",
    "name": "Merlin1",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Merlin2",
    "name": "Merlin2",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Mike",
    "name": "Mike",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Mini",
    "name": "Mini",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Mirror",
    "name": "Mirror",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Mnemonic",
    "name": "Mnemonic",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Modular",
    "name": "Modular",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Morse",
    "name": "Morse",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Morse2",
    "name": "Morse2",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Moscow",
    "name": "Moscow",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Mshebrew210",
    "name": "Mshebrew210",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Muzzle",
    "name": "Muzzle",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "NScript",
    "name": "NScript",
    "style": "script",
    "heightLevel": 2
  },
  {
    "id": "NT Greek",
    "name": "NT Greek",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "NV Script",
    "name": "NV Script",
    "style": "script",
    "heightLevel": 3
  },
  {
    "id": "Nancyj-Fancy",
    "name": "Nancyj Fancy",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Nancyj-Improved",
    "name": "Nancyj Improved",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Nancyj-Underlined",
    "name": "Nancyj Underlined",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Nancyj",
    "name": "Nancyj",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Nipples",
    "name": "Nipples",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "O8",
    "name": "O8",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "OS2",
    "name": "OS2",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Octal",
    "name": "Octal",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Ogre",
    "name": "Ogre",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Old Banner",
    "name": "Old Banner",
    "style": "block",
    "heightLevel": 2
  },
  {
    "id": "Patorjk's Cheese",
    "name": "Patorjk'S Cheese",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Patorjk-HeX",
    "name": "Patorjk HeX",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Pawp",
    "name": "Pawp",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Peaks Slant",
    "name": "Peaks Slant",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Peaks",
    "name": "Peaks",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Pebbles",
    "name": "Pebbles",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Pepper",
    "name": "Pepper",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Poison",
    "name": "Poison",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Puffy",
    "name": "Puffy",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Puzzle",
    "name": "Puzzle",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Pyramid",
    "name": "Pyramid",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Rammstein",
    "name": "Rammstein",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Rectangles",
    "name": "Rectangles",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Red Phoenix",
    "name": "Red Phoenix",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Relief",
    "name": "Relief",
    "style": "3d",
    "heightLevel": 2
  },
  {
    "id": "Relief2",
    "name": "Relief2",
    "style": "3d",
    "heightLevel": 2
  },
  {
    "id": "Reverse",
    "name": "Reverse",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Roman",
    "name": "Roman",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Rot13",
    "name": "Rot13",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Rotated",
    "name": "Rotated",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Rounded",
    "name": "Rounded",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Rowan Cap",
    "name": "Rowan Cap",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Rozzo",
    "name": "Rozzo",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Runic",
    "name": "Runic",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Runyc",
    "name": "Runyc",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "S Blood",
    "name": "S Blood",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "SL Script",
    "name": "SL Script",
    "style": "script",
    "heightLevel": 2
  },
  {
    "id": "Santa Clara",
    "name": "Santa Clara",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Script",
    "name": "Script",
    "style": "script",
    "heightLevel": 2
  },
  {
    "id": "Serifcap",
    "name": "Serifcap",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Shadow",
    "name": "Shadow",
    "style": "3d",
    "heightLevel": 2
  },
  {
    "id": "Shimrod",
    "name": "Shimrod",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Short",
    "name": "Short",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Slant Relief",
    "name": "Slant Relief",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "Slant",
    "name": "Slant",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Slide",
    "name": "Slide",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Small Caps",
    "name": "Small Caps",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Small Isometric1",
    "name": "Small Isometric1",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Small Keyboard",
    "name": "Small Keyboard",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Small Poison",
    "name": "Small Poison",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Small Script",
    "name": "Small Script",
    "style": "script",
    "heightLevel": 2
  },
  {
    "id": "Small Shadow",
    "name": "Small Shadow",
    "style": "3d",
    "heightLevel": 2
  },
  {
    "id": "Small Slant",
    "name": "Small Slant",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Small Tengwar",
    "name": "Small Tengwar",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Small",
    "name": "Small",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Soft",
    "name": "Soft",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Speed",
    "name": "Speed",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Spliff",
    "name": "Spliff",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Stacey",
    "name": "Stacey",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Stampate",
    "name": "Stampate",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Stampatello",
    "name": "Stampatello",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Standard",
    "name": "Standard",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Star Strips",
    "name": "Star Strips",
    "style": "fun",
    "heightLevel": 3
  },
  {
    "id": "Star Wars",
    "name": "Star Wars",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "Stellar",
    "name": "Stellar",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Stforek",
    "name": "Stforek",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Stick Letters",
    "name": "Stick Letters",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Stop",
    "name": "Stop",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Straight",
    "name": "Straight",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Stronger Than All",
    "name": "Stronger Than All",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Sub-Zero",
    "name": "Sub Zero",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Swamp Land",
    "name": "Swamp Land",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Swan",
    "name": "Swan",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Sweet",
    "name": "Sweet",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "THIS",
    "name": "THIS",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Tanja",
    "name": "Tanja",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Tengwar",
    "name": "Tengwar",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Term",
    "name": "Term",
    "style": "retro",
    "heightLevel": 2
  },
  {
    "id": "Test1",
    "name": "Test1",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "The Edge",
    "name": "The Edge",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Thick",
    "name": "Thick",
    "style": "block",
    "heightLevel": 2
  },
  {
    "id": "Thin",
    "name": "Thin",
    "style": "thin",
    "heightLevel": 2
  },
  {
    "id": "Thorned",
    "name": "Thorned",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Three Point",
    "name": "Three Point",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "Ticks Slant",
    "name": "Ticks Slant",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Ticks",
    "name": "Ticks",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Tiles",
    "name": "Tiles",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Tinker-Toy",
    "name": "Tinker Toy",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Tombstone",
    "name": "Tombstone",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Train",
    "name": "Train",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Trek",
    "name": "Trek",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Tsalagi",
    "name": "Tsalagi",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Tubes-Regular",
    "name": "Tubes Regular",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Tubes-Smushed",
    "name": "Tubes Smushed",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Tubular",
    "name": "Tubular",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Twisted",
    "name": "Twisted",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Two Point",
    "name": "Two Point",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "USA Flag",
    "name": "USA Flag",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Univers",
    "name": "Univers",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Varsity",
    "name": "Varsity",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Wavy",
    "name": "Wavy",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Weird",
    "name": "Weird",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "Wet Letter",
    "name": "Wet Letter",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "Whimsy",
    "name": "Whimsy",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "Wow",
    "name": "Wow",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "alligator3",
    "name": "Alligator3",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "amc3line",
    "name": "Amc3line",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "amc3liv1",
    "name": "Amc3liv1",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "amcaaa01",
    "name": "Amcaaa01",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "amcneko",
    "name": "Amcneko",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "amcrazo2",
    "name": "Amcrazo2",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "amcrazor",
    "name": "Amcrazor",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "amcslash",
    "name": "Amcslash",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "amcslder",
    "name": "Amcslder",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "amcthin",
    "name": "Amcthin",
    "style": "thin",
    "heightLevel": 2
  },
  {
    "id": "amctubes",
    "name": "Amctubes",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "amcun1",
    "name": "Amcun1",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "ascii_new_roman",
    "name": "Ascii New Roman",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "bigchief",
    "name": "Bigchief",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "broadway_kb",
    "name": "Broadway Kb",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "calgphy2",
    "name": "Calgphy2",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "cosmic",
    "name": "Cosmic",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "dancingfont",
    "name": "Dancingfont",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "defleppard",
    "name": "Defleppard",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "dietcola",
    "name": "Dietcola",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "dosrebel",
    "name": "Dosrebel",
    "style": "retro",
    "heightLevel": 3
  },
  {
    "id": "dotmatrix",
    "name": "Dotmatrix",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "doubleshorts",
    "name": "Doubleshorts",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "drpepper",
    "name": "Drpepper",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "eftichess",
    "name": "Eftichess",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "eftifont",
    "name": "Eftifont",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "eftipiti",
    "name": "Eftipiti",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "eftirobot",
    "name": "Eftirobot",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "eftitalic",
    "name": "Eftitalic",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "eftiwall",
    "name": "Eftiwall",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "eftiwater",
    "name": "Eftiwater",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "fire_font-k",
    "name": "Fire Font K",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "fire_font-s",
    "name": "Fire Font S",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "flowerpower",
    "name": "Flowerpower",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "fourtops",
    "name": "Fourtops",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "funface",
    "name": "Funface",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "funfaces",
    "name": "Funfaces",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "halfiwi",
    "name": "Halfiwi",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "heart_left",
    "name": "Heart Left",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "heart_right",
    "name": "Heart Right",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "henry3d",
    "name": "Henry3d",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "horizontalleft",
    "name": "Horizontalleft",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "horizontalright",
    "name": "Horizontalright",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "koholint",
    "name": "Koholint",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "kompaktblk",
    "name": "Kompaktblk",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "kontoslant",
    "name": "Kontoslant",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "larry3d",
    "name": "Larry3d",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "lildevil",
    "name": "Lildevil",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "lineblocks",
    "name": "Lineblocks",
    "style": "block",
    "heightLevel": 2
  },
  {
    "id": "maxiwi",
    "name": "Maxiwi",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "miniwi",
    "name": "Miniwi",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "mono9",
    "name": "Mono9",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "ntgreek",
    "name": "Ntgreek",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "oldbanner",
    "name": "Oldbanner",
    "style": "block",
    "heightLevel": 2
  },
  {
    "id": "peaksslant",
    "name": "Peaksslant",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "red_phoenix",
    "name": "Red Phoenix",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "rev",
    "name": "Rev",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "rowancap",
    "name": "Rowancap",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "s-relief",
    "name": "S Relief",
    "style": "3d",
    "heightLevel": 3
  },
  {
    "id": "santaclara",
    "name": "Santaclara",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "sblood",
    "name": "Sblood",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "six-fo",
    "name": "Six Fo",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "slscript",
    "name": "Slscript",
    "style": "script",
    "heightLevel": 2
  },
  {
    "id": "smallcaps",
    "name": "Smallcaps",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "smisome1",
    "name": "Smisome1",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "smkeyboard",
    "name": "Smkeyboard",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "smpoison",
    "name": "Smpoison",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "smscript",
    "name": "Smscript",
    "style": "script",
    "heightLevel": 2
  },
  {
    "id": "smshadow",
    "name": "Smshadow",
    "style": "3d",
    "heightLevel": 2
  },
  {
    "id": "smslant",
    "name": "Smslant",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "smtengwar",
    "name": "Smtengwar",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "starstrips",
    "name": "Starstrips",
    "style": "fun",
    "heightLevel": 3
  },
  {
    "id": "starwars",
    "name": "Starwars",
    "style": "fun",
    "heightLevel": 2
  },
  {
    "id": "stencil",
    "name": "Stencil",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "swampland",
    "name": "Swampland",
    "style": "classic",
    "heightLevel": 3
  },
  {
    "id": "terminus",
    "name": "Terminus",
    "style": "retro",
    "heightLevel": 2
  },
  {
    "id": "terminus_dots",
    "name": "Terminus Dots",
    "style": "retro",
    "heightLevel": 1
  },
  {
    "id": "threepoint",
    "name": "Threepoint",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "ticksslant",
    "name": "Ticksslant",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "twopoint",
    "name": "Twopoint",
    "style": "classic",
    "heightLevel": 1
  },
  {
    "id": "ublk",
    "name": "Ublk",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "usaflag",
    "name": "Usaflag",
    "style": "classic",
    "heightLevel": 2
  },
  {
    "id": "wetletter",
    "name": "Wetletter",
    "style": "classic",
    "heightLevel": 2
  }
] as const;

export function getFontById(id: string): FontMeta | undefined {
  return allFontsMeta.find(f => f.id === id);
}
